name: Continuous Integration
on:
  # Push
  push:
  # Manual request
  workflow_dispatch:
  # Pull request
  pull_request:

jobs:
  build:
    name: Unit Test All
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with pycodestyle
        run: |
          pycodestyle ./lapidary/*.py
          pycodestyle ./tests/*.py
      - name: Lint with mypy
        run: |
          mypy . --ignore-missing-imports
      - name: Test with pytest
        run: |
          pytest
